"""Concrete read-only normalization; independent claims are never inferred from logs."""
import copy
from .binding_consumer import require
from .native_v2 import addr,hx,COLLATERAL,ASSET
from .identify_account import CONTRACT
from .compare_accounts import D6
from .core import digest,dec
from .bounded_reconciliation import SCOPE

class PinnedEvidenceAuthority:
    """Independent provider identity + exact reviewed payload pins. No default trust.
    Pins are externally supplied approvals, never generated by the reader itself.
    """
    def __init__(self,provider,pins,*,fixture_only=False):self.provider=provider;self.pins=copy.deepcopy(pins);self.fixture_only=fixture_only
    def verify(self,r,*,role='result'):
        if type(r) is not dict or role not in ('source','result'):return False
        approved=self.pins.get((r.get('kind'),role))
        return (r.get('provider_identity')==self.provider and r.get('source_digest')==digest(r.get('payload')) and approved==r.get('source_digest') and r.get('scope')==SCOPE and (r.get('fixture_only') is True)==self.fixture_only)

class ConcreteReaders:
    def __init__(self,rpc,*,account,tokens,market,baseline_block,closing_block):
        require(addr(account)==addr(D6),'ACCOUNT_MAPPING');hx(market,32)
        require(type(tokens) is list and 1<=len(tokens)<=2 and len(set(tokens))==len(tokens) and all(type(t) is str and t.isdigit() and 0<int(t)<2**256 for t in tokens),'TOKEN_MAPPING')
        require(baseline_block in rpc.blocks and closing_block in rpc.blocks and baseline_block<=closing_block,'SNAPSHOT_BLOCK_SCOPE')
        self.rpc=rpc;self.account=account;self.tokens=tokens;self.market=market;self.lo=baseline_block;self.hi=closing_block
        self.allowed=[]
        for n in (self.lo,self.hi):
            self.allowed.append(self.params(COLLATERAL,'0x70a08231'+account[2:].lower().rjust(64,'0'),n))
            for t in tokens:self.allowed.append(self.params(ASSET,'0x00fdd58e'+account[2:].lower().rjust(64,'0')+format(int(t),'064x'),n))
        rpc.call_allowlist=copy.deepcopy(self.allowed)
    def params(self,to,data,n):return [dict(to=to,data=data),hex(n)]
    async def snapshot(self,n):
        require(n in (self.lo,self.hi),'SNAPSHOT_SCOPE');start=self.rpc.clock();await self.rpc.canonical(n);values=[];raw=[]
        for p in self.allowed:
            if p[1]!=hex(n):continue
            r=await self.rpc.call('eth_call',p);values.append(str(int(r['payload'],16)));raw.append(r)
        await self.rpc.canonical(n)
        return dict(chain_id=137,collateral_symbol='pUSD',collateral_decimals=6,collateral_contract=CONTRACT,asset_contract='0x4D97DCd97eC945f40cF65F87097ACe5EA0476045',cash_raw=values[0],assets_raw=dict(zip(self.tokens,values[1:])),block_number=n,block_hash=self.rpc.blocks[n],read_start_ms=start,observed_ms=self.rpc.clock(),raw_reads=raw)
    async def finality(self,claim):
        # A provider's finalized block claim must be authenticated independently at envelope boundary.
        require(type(claim) is dict and type(claim.get('finalized_number')) is int and claim['finalized_number']>=self.hi and claim.get('policy')=='PROVIDER_FINALIZED_PLUS_HASH_RECHECK','FINALITY_UNKNOWN')
        start=self.rpc.clock();canonical={str(n):h for n,h in self.rpc.blocks.items()};rechecked={}
        for n in self.rpc.blocks:
            r=await self.rpc.canonical(n);rechecked[str(n)]=r['payload']['hash']
        return dict(policy=claim['policy'],finalized_number=claim['finalized_number'],read_start_ms=start,recheck_read_start_ms=start,observed_ms=self.rpc.clock(),canonical_hashes=canonical,rechecked_hashes=rechecked,source_claim=copy.deepcopy(claim))
    def terminal(self,raw_orders,known):
        require(type(raw_orders) is list and len(raw_orders)==len(known),'TERMINAL_SCOPE');out=[];seen=set()
        for r in raw_orders:
            oid=r['order_id'];require(oid in known and oid not in seen and r['status'] in ('FILLED','CANCELED','EXPIRED'),'TERMINAL_UNKNOWN');seen.add(oid)
            require(type(r['cumulative_shares']) is str and dec(r['cumulative_shares'])>=0 and type(r['read_start_ms']) is int and type(r['observed_ms']) is int and r['read_start_ms']<=r['observed_ms']<=self.rpc.clock(),'TERMINAL_RAW')
            out.append(copy.deepcopy(r))
        return {'orders':out}
    def coverage(self,claim,observations,receipts):
        require(type(claim) is dict and claim.get('pagination_complete') is True and claim.get('ws_gaps')==[] and claim.get('foreign_activity')==[] and claim.get('unexplained_mutations')==[],'COVERAGE_UNKNOWN')
        require(claim.get('from_exclusive')==self.lo and claim.get('to_inclusive')==self.hi,'COVERAGE_RANGE')
        receipt_logs={(l['transactionHash'],l['logIndex']):l for r in receipts for l in r['receipt']['logs']}
        seen=set()
        for observation in observations:
            for l in observation['logs']:
                key=(l['transactionHash'],l['logIndex']);require(key in receipt_logs and receipt_logs[key]==l and key not in seen,'FOREIGN_MUTATION_OR_LOG');seen.add(key)
        # Still only a consistency check: independent claim required, never global completeness.
        return copy.deepcopy(claim)
